### ISSUE TITLE
Create Level: Pause Broken

### ISSUE THREAD

**Issue by hesto2** [hesto2/PygameStarter#25]
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    C.GAME.run()
  File "/Users/carterhesterman/Dev/Python/PygameStarter/gameMaster.py", line 29, in run
    self.display.tick()
  File "/Users/carterhesterman/Dev/Python/PygameStarter/displays/levels/createLevel.py", line 55, in tick
    subEntity.tick()
  File "/Users/carterhesterman/Dev/Python/PygameStarter/entities/gui/timer.py", line 24, in tick
    if current_time < C.GAME.display.start_time:
AttributeError: 'CreateLevel' object has no attribute 'start_time'

**Comment by hesto2** [comment]
This only happens when a game is started and then exited before going to the create level screen
